version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.alpine-armv7hf
    container_name: aws-iot-greengrass
    image: alpine/greengrass:1.9.2-armv7hf
    volumes:
      - ./certs:/greengrass/certs
      - ./config:/greengrass/config
      - ./deployment:/greengrass/ggc/deployment
      - ./log:/greengrass/ggc/var/log
    ports:
      - "8883:8883"
    entrypoint: "/greengrass-entrypoint.sh"
